apiVersion: apps/v1
kind: Deployment
metadata:
  name: weatherapi
  labels:
    app: weatherapi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weatherapi
  template:
    metadata:
      labels:
        app: weatherapi
    spec:
      containers:
        - name: weatherapi
          image: gpshackacr.azurecr.io/weatherapi:d577d33fe949221fccb0b2b0374b5689e1e8b602
          ports:
            - containerPort: 5000