# Default values for autoql-post-processor-service.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

namespace: staging

rbac:
  enabled: false

# horizontal pod autoscaler
hpa: {}
serviceAccountName:
app:
releaseId:
image:
  repository: us.gcr.io/staging-245514/autoql-post-processor-service
  tag: v1.0.0
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/tls-acme: "true"
    # kubernetes.io/ingress.class: "gce"
    # gcloud compute addresses create --global camel-service-test-ingress-ip
    # kubernetes.io/ingress.global-static-ip-name: camel-service-test-ingress-ip
  path: /*
  # hosts:
  #   - camel-service.services.backend.test.chata.ai
  # tls:
  #   - secretName: camel-svc-tls
  #     hosts:
  #       - camel-service.services.backend.test.chata.ai
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

livenessProbe: {}
readinessProbe: {}
sidecars: []
initContainers: []

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #  cpu: 100m
  #  memory: 128Mi
  # requests:
  #  cpu: 100m
  #  memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
