{{- if .Values.ingress.enabled -}}
{{- $fullName := include "autoql-post-processor-service.fullname" . -}}
{{- $servicePort := .Values.service.portName -}}
{{- $ingressPath := .Values.ingress.path -}}
apiVersion: extensions/v1
kind: Ingress
metadata:
  namespace: {{ .Values.namespace }}
  name: {{ $fullName }}
  labels:
    releaseId: {{ .Values.releaseId }}
    app: {{ .Values.app }}
    chart: {{ template "autoql-post-processor-service.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
{{- with .Values.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
{{- if .Values.ingress.tls }}
  tls:
  {{- range .Values.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.ingress.hosts }}
    - host: {{ . }}
      http:
        paths:
          - path: {{ $ingressPath }}
            backend:
              serviceName: {{ $fullName }}
              servicePort: {{ $servicePort }}
  {{- end }}
{{- end }}
