{{ $global := . }}
{{- range $index, $secret := .Values.secrets }}
apiVersion: v1
type: Opaque
kind: Secret
metadata:
  name: {{ $secret.name }}
  namespace: {{ $global.Values.namespace }}
{{- with $secret.values }}
data:
{{ toYaml . | indent 2}}
{{- end }}
---
{{- end }}
